// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvwyHx878v1_ri1tSLdRUEH_zZb7EkO4',
    appId: '1:564965677357:web:f767a323f637596f5a5ba4',
    messagingSenderId: '564965677357',
    projectId: 'tak-estate-eac42',
    authDomain: 'tak-estate-eac42.firebaseapp.com',
    storageBucket: 'tak-estate-eac42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPPdjflaWcacW5TXKcmuEYK-JXH8hgwQ',
    appId: '1:564965677357:android:fca69fa2ee5facfc5a5ba4',
    messagingSenderId: '564965677357',
    projectId: 'tak-estate-eac42',
    storageBucket: 'tak-estate-eac42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9tJmGn2LB1xjMF7VaSgNUXVSpACDHgk',
    appId: '1:564965677357:ios:5fb12715e8deb5815a5ba4',
    messagingSenderId: '564965677357',
    projectId: 'tak-estate-eac42',
    storageBucket: 'tak-estate-eac42.appspot.com',
    iosBundleId: 'com.jubileesystem.tak.tak',
  );
}
